baseURL = '/'
languageCode = 'en-us'
title = 'Francisco Sosa | fsosam'
theme = "square"
paginate = 7

[params]
	author = "Francisco Sosa"
    custom_js = ["js/custom.js"]

    [params.footer]
		trademark	= true
		copyright	= true
		author		= true

		bText		= [
			"| Powered by <a href=\"http://gohugo.io\">Hugo</a>. ",
			"Made with &#10084; <a href=\"https://devureca.com/\">@devureca</a>"
		]

[module]
	[[module.mounts]]
		source = "node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"
		target = "assets/js/bootstrap.bundle.min.js"

[menu]
	[[menu.main]]
		identifier	= "item1"
		name		= "Item1"
		url 		= "/item1/"
		weight		= 1

	[[menu.main]]
		identifier	= "item2"
		name		= "Item2"
		url 		= "/posts/"
		weight		= 2

	[[menu.main]]
		identifier	= "item3"
		name		= "Item3"
		url 		= "/item3/"
		weight		= 3
